#!/usr/bin/env python3
"""Generate a self-contained switch for static sites, including subpath hosting."""
from pathlib import Path
import json
root = Path(__file__).resolve().parents[1]
pairs = json.loads((root / 'language-map.json').read_text(encoding='utf-8'))
script = '''// Generated by tools/build_language_switch.py from language-map.json.
const languagePages = __PAIRS__;
document.addEventListener('DOMContentLoaded', () => {
  const links = Array.from(document.querySelectorAll('.navbar a.nav-link'));
  const english = links.find(a => a.textContent.trim() === 'English');
  const chinese = links.find(a => a.textContent.trim() === '中文');
  if (!english || !chinese) return;
  // Quarto already makes the English home link relative to the current page.
  const root = new URL('.', english.href);
  let path = decodeURIComponent(location.pathname.slice(root.pathname.length));
  if (!path || path.endsWith('/')) path += 'index.html';
  const pair = languagePages.find(p => p.en === path || p.zh === path);
  if (!pair) return;
  const current = pair.zh === path ? 'zh' : 'en';
  for (const [language, anchor] of [['en', english], ['zh', chinese]]) {
    anchor.href = new URL(pair[language], root).href;
    anchor.hreflang = language === 'zh' ? 'zh-CN' : 'en';
    anchor.lang = anchor.hreflang;
    anchor.classList.toggle('active', language === current);
    anchor.setAttribute('aria-label', language === 'zh' ? '阅读本页中文版' : 'Read this page in English');
    if (language === current) anchor.setAttribute('aria-current', 'page');
    else anchor.removeAttribute('aria-current');
  }
  if (current === 'zh') {
    const title = document.querySelector('.navbar-title');
    if (title) title.textContent = '一步步理解 Java 虚拟机';
    const brand = document.querySelector('.navbar-brand');
    if (brand) brand.href = new URL('zh/index.html', root).href;
  }
});
'''.replace('__PAIRS__', json.dumps(pairs, ensure_ascii=False, indent=2))
(root / 'filters/language-switch.js').write_text(script, encoding='utf-8')
